extends:
  - eslint:recommended
  - react-app
  - react-app/jest
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
    node: true
rules:
  'prettier/prettier': warn
  'no-console': warn
  'import/no-default-export': error
  # check for unused arguments (overriding extended rule)
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: after-used
      ignoreRestSiblings: false
  import/no-unused-modules:
    - warn
    - unusedExports: true
      ignoreExports:
        - cypress.config.ts
        # TODO for now we accept mess in ldo shapes
        # since it is a generated code, and it's in development
        # eventually we may want to remove unused shapes
        - src/ldo
