name: Notify matrix room when a pull request is merged (or rebased)

on:
  pull_request:
    types:
      - closed

jobs:
  ping_matrix_when_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: send message for merge
        uses: s3krit/matrix-message-action@v0.0.3
        with:
          room_id: ${{ secrets.MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: 'A change [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}) was merged.'
          server: 'matrix.org'
      - run: |
          echo The PR was merged
